---
id: 20191130_kagoshima_keynote
base_name: 20191130_kagoshima_keynote
tags: []
presentation_date: '2019-11-30'
presentation_start_time: 
presentation_end_time: 
version: 2019.11.30.0
licenses: []
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :markdown
  name: Mayumi Emori
  email: mayumi.emori@gmail.com
  rubygems_user: 
  slideshare_user: 
  speaker_deck_user: 
